### PR TITLE
Fix how bundle IDs are getting defined for individual bundles

### LINKED ISSUE #5250: [react native 0.82.0] Debug ID was not found in the bundle. Call `options.sentryBundleCallback` if you are using a custom serializer.
### What React Native libraries do you use?

React Navigation, RN New Architecture

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

7.2.0

### How does your development environment look like?

````
⬇  Place the `npx react-native@latest info` output here. ⬇

info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.26100
  CPU: (22) x64 Intel(R) Core(TM) Ultra 9 185H
  Memory: 3.94 GB / 31.61 GB
Binaries:
  Node:
    version: 22.17.0
    path: D:\Program\Development\Environment\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Users\Coz\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 11.6.1
    path: D:\Program\Development\Environment\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.14.36429.23 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 17.0.2
    path: D:\Program\Development\Environment\Java\jdk-17.0.2\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.0
    wanted: 20.0.0
  react:
    installed: 19.1.1
    wanted: 19.1.1
  react-native:
    installed: 0.82.0
    wanted: 0.82.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

````

### Sentry.init()

````js
Sentry.init({
  dsn: 'https://...@sentry.io/...',

  // Adds more context data to events (IP address, cookies, user, etc.)
  // For more information, visit: https://docs.sentry.io/platforms/react-native/data-management/data-collected/
  sendDefaultPii: true,

  // Configure Session Replay
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1,
  integrations: [Sentry.mobileReplayIntegration(), Sentry.feedbackIntegration()],

  // uncomment the line below to enable Spotlight (https://spotlightjs.com)
  // spotlight: __DEV__,
});
````

### Steps to Reproduce

1. create an react-native 0.82.0 repo (using gradle 9.0.0, by this patch: https://github.com/getsentry/sentry-react-native/issues/5192#issuecomment-3383975849)
2. load an dynamic module like this:
```jsx
const lazyComponent = React.lazy(() => import('./tabs/LazyLoadPage'))
...
<lazyComponent />
```
3. run the app on real device (I am running on android 15 device)
4. before load the `lazyComponent` the app run success
5. load the `lazyComponent` (by click the button), the error raised:
```
Debug ID was not found in the bundle. Call `options.sentryBundleCallback` if you are using a custom serializer.
```

---

the detail stack trace can be found below, and it seems like the function `determineDebugIdFromBundleSource`'s problem (not very sure):

https://github.com/getsentry/sentry-react-native/blob/5ee3314125fe4c01a1e998efc90708cb39b99899/packages/core/src/js/tools/sentryMetroSerializer.ts#L76-L85

`determineDebugIdFromBundleSource` was at here:

https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/40f918458ed449d8b3eabaf64d13c08218213f65/packages/bundler-plugin-core/src/debug-id-upload.ts#L293-L294

### Expected Result

no error raised

### Actual Result

stack trace:

```
 BUNDLE  src\views\pages\DebugMenu\tabs/DebugMenuAll.tsx
 ERROR  Error: Debug ID was not found in the bundle. Call `options.sentryBundleCallback` if you are using a custom serializer.
    at E:\Project\spidermemos-app\node_modules\@sentry\react-native\dist\js\tools\sentryMetroSerializer.js:65:23
    at Generator.next (<anonymous>)
    at fulfilled (E:\Project\spidermemos-app\node_modules\@sentry\react-native\dist\js\tools\sentryMetroSerializer.js:5:58)
```

Image

Image

Image

### PR DESCRIPTION
**Pull request by alwx**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Fixes #5250

Here is the root cause:
- Lazy-loaded chunks are serialized separately with their own `preModules` array
- The debug ID module is only added to the main bundle's preModules
- When processing a lazy chunk, determineDebugIdFromBundleSource() can't find the debug ID → returns null
- The code throws an error instead of handling this gracefully

The solution is to generate bundle IDs for individual code chunks.
That needs to be done because when Metro 0.83.2 stopped importing `BabelSourceMapSegment` from `@babel/generator` and defined it locally, it subtly changed the source map output format.

## :pencil: Checklist

- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: packages/core/src/js/tools/sentryMetroSerializer.ts [hunk 1]
```diff
@@ -74,11 +74,19 @@ export const createSentryMetroSerializer = (customSerializer?: MetroSerializer):
...
+      // calculate the debug ID from the bundle content.
+      // This ensures Metro 0.83.2+ code-split bundles get debug IDs.
+      // That needs to be done because when Metro 0.83.2 stopped importing `BabelSourceMapSegment`
+      // from `@babel/generator` and defined it locally, it subtly changed the source map output format.
+      // https://github.com/facebook/metro/blob/main/packages/metro-source-map/src/source-map.js#L47
+      const hash = crypto.createHash('md5');
+      hash.update(bundleCode);
+      debugId = stringToUUID(hash.digest('hex'));
+      // eslint-disable-next-line no-console
+      console.log('info ' + `Bundle Debug ID (calculated): ${debugId}`);
```
Comment (antonis) [inline packages/core/src/js/tools/sentryMetroSerializer.ts:89]: q: Wdyt of adding [new tests](https://github.com/getsentry/sentry-react-native/blob/main/packages/core/test/tools/sentryMetroSerializer.test.ts) for the fallback flow?

File: packages/core/src/js/tools/sentryMetroSerializer.ts [hunk 2]
```diff
@@ -74,11 +74,19 @@ export const createSentryMetroSerializer = (customSerializer?: MetroSerializer):
...
-      throw new Error(
-        'Debug ID was not found in the bundle. Call `options.sentryBundleCallback` if you are using a custom serializer.',
-      );
+      // For lazy-loaded chunks or bundles without the debug ID module,
+      // calculate the debug ID from the bundle content.
+      // This ensures Metro 0.83.2+ code-split bundles get debug IDs.
+      // That needs to be done because when Metro 0.83.2 stopped importing `BabelSourceMapSegment`
+      // from `@babel/generator` and defined it locally, it subtly changed the source map output format.
+      // https://github.com/facebook/metro/blob/main/packages/metro-source-map/src/source-map.js#L47
+      const hash = crypto.createHash('md5');
```
Comment (antonis) [inline packages/core/src/js/tools/sentryMetroSerializer.ts:85]: nit: could we reuse the `calculateDebugId` function [below](https://github.com/getsentry/sentry-react-native/pull/5342/files#diff-6b6980214a2fdcfc0b537257f2356d87503d79ba8273771e648373359e18be19R156)?

**Review by antonis — APPROVED** [review]
Awesome work identifying and fixing this @alwx 🎸 
The fallback approach looks solid to me. Added a couple of questions but overall LGTM.

File: CHANGELOG.md [hunk 3]
```diff
@@ -11,6 +11,7 @@
 ### Fixes
 
 - Android SDK not being disabled when `options.enabled` is set to `false`  ([#5334](https://github.com/getsentry/sentry-react-native/pull/5334))
+- Fixes how bundle IDs are getting defined for individual bundles ([#5342](https://github.com/getsentry/sentry-react-native/pull/5342))
```
Comment (antonis) [inline CHANGELOG.md:14]: We could add a reference to 0.83.2+ here

File: packages/core/src/js/tools/sentryMetroSerializer.ts (hunk 1 above)
Comment (lucas-zimerman) [reply packages/core/src/js/tools/sentryMetroSerializer.ts:89]: Agreed that we should at least add one test.

Comment (alwx) [reply packages/core/src/js/tools/sentryMetroSerializer.ts:89]: I've added a test for it (in fact, there were zero tests to check the debugID being added even before that)

File: packages/core/src/js/tools/sentryMetroSerializer.ts (hunk 2 above)
Comment (alwx) [reply packages/core/src/js/tools/sentryMetroSerializer.ts:85]: I've decided not to reuse that function because it has some extra functionality that's not needed here (it operates with the Bundle object and iterates over modules as well). That functionality could of course be extracted to another function but I'd rather do it separately along with tests for that.

Comment (antonis) [reply packages/core/src/js/tools/sentryMetroSerializer.ts:85]: Sounds good 👍

**Comment by antonis** [comment]
I'll proceed with merging since the failing tests are not relevant with this PR:
- [End-to-End Tests V2 / metrics (legacy, android) (pull_request)](https://github.com/getsentry/sentry-react-native/actions/runs/19235953954/job/54985862371?pr=5342)
- [End-to-End Tests V2 / metrics (new, android) (pull_request)](https://github.com/getsentry/sentry-react-native/actions/runs/19235953954/job/54985862365?pr=5342)
- [End-to-End Tests V2 / Test RN 0.81.0 legacy hermes ios production no (pull_request)](https://github.com/getsentry/sentry-react-native/actions/runs/19235953954/job/54989184210?pr=5342)
