### PR TITLE
fix: enableNative: false should take precedence over autoInitializeNativeSdk: false

### LINKED ISSUE #1461: Native SDK still trying to initialize after passing `enableNative: false`
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"@sentry/react-native": "^2.4.1"

### Steps to Reproduce

1. init new react-native project
2. call 
```
Sentry.init({
  enableNative: false,
  enableNativeNagger: false,
  enableNativeCrashHandling: false,
  autoInitializeNativeSdk: false,
});
``` 

(there's a lot of native options so i just disabled them all)

### Expected Result

no error

### Actual Result

`SentryError: Native Client is not available, can't start on native.`

### PR DESCRIPTION
**Pull request by jennmueng**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Setting both `enableNative: false` and `autoInitializeNativeSdk: false` will now prioritize `enableNative: false`.

## :bulb: Motivation and Context

Setting both `enableNative: false` and `autoInitializeNativeSdk: false` ignores `enableNative: false` and only considers `autoInitializeNativeSdk` thus it would not initialize the native SDK but not set `NATIVE.enableNative: false`, allowing calls to still be made to the bridge.

Fixes #1461

## :green_heart: How did you test it?
Added a test for this precedence, also added tests for each of the scope sync methods as well.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: src/js/wrapper.ts [hunk 1]
```diff
@@ -85,25 +85,28 @@ export const NATIVE = {
...
+        logger.warn("Note: Native Sentry SDK is disabled.");
+      }
+      this.enableNative = false;
+      return false;
+    }
     if (!options.autoInitializeNativeSdk) {
       if (options.enableNativeNagger) {
-        logger.warn("Note: Native Sentry SDK was not initialized.");
+        logger.warn(
+          "Note: Native Sentry SDK was not initialized automatically, you will need to initialize it manually. If you wish to disable the native SDK, pass enableNative: false"
```
Comment (bruno-garcia) [inline src/js/wrapper.ts:98]: L:
```suggestion
          "Note: Native Sentry SDK was not initialized automatically, you will need to initialize it manually. If you wish to disable the native SDK and get rid of this warning, pass enableNative: false"
```

**Review by bruno-garcia — APPROVED** [review]
