### PR TITLE
fix: Warn when promise rejections won't be caught

### LINKED ISSUE #1077: Unhandled promises are not logged at all (iOS and Android)
**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** "@sentry/react-native": "^1.7.2",

**`react-native` version:** "react-native": "^0.63.2",

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No issue was created

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // no extra options
});
```

---
**I have following issue:**

Normal exceptions are logged to Sentry.io just fine, but unhandled promises are not logged at all.  My understanding is that this should happen by default.  I do get a yellow box showing the unhandled exception but it seems that Sentry never sees it.

This repros on both Android and iOS.

**Steps to reproduce:**
1. Install sentry with minimal config
2. Generate an unhandled promise rejection

**Actual result:**

Yellow box appears but no error logged to sentry.io

image

**Expected result:**

Unhandled promise rejections are logged to sentry.io

### PR DESCRIPTION
**Pull request by jennmueng**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

This fix will appear to not work in the original sample app in this repo as our SDK will use the promise library from the root folder instead of the one inside the sample folder that React Native uses. Thus the end to end tests have been updated to use a packaged version of the SDK via `yalc`. This way the promise rejection handler will be tested.

e2e test workflow will run the script `sample/scripts/prepareConfigsForTesting.sh` which will swap out the babel config and the metro config to the testing one which will use the packaged SDK instead.

Extra
- Removes Flipper from Android sample
- Also the behavior of the promise rejection handler will follow the behavior of the default react native handler rather than just calling. a console.warn like before.

## :bulb: Motivation and Context

Fixes #1077

## :green_heart: How did you test it?
End to end tests will now package the SDK and test the unhandled promise instrumentation.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps
Merge docs PR https://github.com/getsentry/sentry-docs/pull/4392

### CODE REVIEW

File: src/js/integrations/reactnativeerrorhandlers.ts [hunk 1]
```diff
@@ -51,66 +51,79 @@ export class ReactNativeErrorHandlers implements Integration {
...
-        if ("_onHandle" in _global.Promise && "_onReject" in _global.Promise) {
-          _global.Promise._onHandle = _onHandle;
-          _global.Promise._onReject = _onReject;
-        } else if ("_Y" in _global.Promise && "_Z" in _global.Promise) {
-          _global.Promise._Y = _onHandle;
-          _global.Promise._Z = _onReject;
-        }
+      if (Promise !== _global.Promise) {
+        logger.warn(
+          "Unhandled promise rejections will not be caught by Sentry. Read about how to fix this on our troubleshooting page."
```
Comment (marandaneto) [inline src/js/integrations/reactnativeerrorhandlers.ts:117]: link to the docs once merged

Comment (jennmueng) [reply src/js/integrations/reactnativeerrorhandlers.ts:117]: @marandaneto Do we want to directly have a link to the docs in the warning message?

**Comment by jennmueng** [comment]
For some reason the android emulator for the e2e test isn't working, says app never started. Works locally... going to keep debugging this

**Comment by jennmueng** [comment]
Accidentally hit close

File: sample/android/app/src/main/java/io/sentry/sample/MainApplication.java [hunk 2]
```diff
@@ -25,7 +25,19 @@ public boolean getUseDeveloperSupport() {
...
+      for (ReactPackage pkg : packages) {
+        if (pkg instanceof RNSentryPackage) {
+          packageExists = true;
+          break;
+        }
+      }
+
+      if (!packageExists) {
+        packages.add(new RNSentryPackage());
+      }
```
Comment (marandaneto) [inline sample/android/app/src/main/java/io/sentry/sample/MainApplication.java:39]: why is this necessary?

File: sample/ios/Podfile [hunk 3]
```diff
@@ -13,7 +13,9 @@ target 'sample' do
   	:hermes_enabled => true
   )
 
-  pod 'RNSentry', :path => '../../RNSentry.podspec'
+  if !ENV['TEST']
+    pod 'RNSentry', :path => '../../RNSentry.podspec'
+  end
```
Comment (marandaneto) [inline sample/ios/Podfile:18]: why do we need that? does that mean that the `test` version don't include RNSentry?

File: sample/src/App.tsx [hunk 4]
```diff
@@ -60,8 +60,8 @@ Sentry.init({
   tracesSampleRate: 1.0,
   // Sets the `release` and `dist` on Sentry events. Make sure this matches EXACTLY with the values on your sourcemaps
   // otherwise they will not work.
-  release: packageVersion,
-  dist: `${packageVersion}.0`,
+  release: '1.2.3',
+  dist: `1.2.3.0`,
```
Comment (marandaneto) [inline sample/src/App.tsx:64]: should we revert this change?

File: src/js/integrations/reactnativeerrorhandlers.ts (hunk 1 above)
Comment (marandaneto) [reply src/js/integrations/reactnativeerrorhandlers.ts:117]: since it mentions the troubleshooting page its fine the way how it is

File: src/js/integrations/reactnativeerrorhandlers.ts [hunk 5]
```diff
@@ -51,66 +51,79 @@ export class ReactNativeErrorHandlers implements Integration {
...
+        onHandled: (_id: string) => {},
+      };
+
+      try {
+        // Here we try to use React Native's original promise rejection handler.
+        // eslint-disable-next-line @typescript-eslint/no-var-requires,@typescript-eslint/no-unsafe-member-access
+        promiseRejectionTrackingOptions = require("react-native/Libraries/promiseRejectionTrackingOptions")
+          .default;
+      } catch (e) {
+        // do nothing, as the user may be running an older version of RN without promiseRejectionTrackingOptions
```
Comment (marandaneto) [inline src/js/integrations/reactnativeerrorhandlers.ts:83]: is it possible to know if the reason is that there is no `promiseRejectionTrackingOptions` at all? wondering if we should log a warn in any other case

**Comment by marandaneto** [comment]
@AbhiPrasad would you mind reviewing this one too? that's a field I don't master, thanks.

File: sample/src/App.tsx [hunk 6]
```diff
@@ -17,7 +17,7 @@ import EndToEndTestsScreen from './screens/EndToEndTestsScreen';
 import ReduxScreen from './screens/ReduxScreen';
 
 import {store} from './reduxApp';
-import {version as packageVersion} from '../../package.json';
+// import {version as packageVersion} from '../../package.json';
```
Comment (bruno-garcia) [inline sample/src/App.tsx:20]:
```suggestion
```

File: sample/android/app/src/main/java/io/sentry/sample/MainApplication.java (hunk 2 above)
Comment (jennmueng) [reply sample/android/app/src/main/java/io/sentry/sample/MainApplication.java:39]: When the SDK is installed via linking to the parent folder for development we need to add the package manually with ` packages.add(new RNSentryPackage())`, however when the SDK is packaged and installed for the e2e tests React Native auto-adds the package already on Android, if the line is there then the app crashes at runtime for duplicate packages.

File: sample/ios/Podfile (hunk 3 above)
Comment (jennmueng) [reply sample/ios/Podfile:18]: The test version has the pod auto-added by React Native, while we're developing using the SDK in the parent folder we need to add it manually.

File: sample/src/App.tsx (hunk 4 above)
Comment (jennmueng) [reply sample/src/App.tsx:64]: We can no longer use the version from the parent folder when the SDK is packaged and the linking to the parent folder is removed so thus why this change here

File: src/js/integrations/reactnativeerrorhandlers.ts (hunk 5 above)
Comment (jennmueng) [reply src/js/integrations/reactnativeerrorhandlers.ts:83]: Hmm I don't think we would need to warn as if the `promiseRejectionTrackingOptions` doesn't exist for any reason the log message in debug mode for the developer just won't be as pretty, all that the `promiseRejectionTrackingOptions` from RN does is just prettify the log messages

File: .github/workflows/e2e.yml [hunk 7]
```diff
@@ -31,12 +31,22 @@ jobs:
...
+      - name: Build SDK
+        run: yarn build
+      - name: Package SDK
+        run: yalc publish
+      - name: Prepare sample for testing
+        working-directory: ./sample
+        run: sh ./scripts/prepareConfigsForTesting.sh
+      - name: Install SDK in sample
+        working-directory: ./sample
+        run: yalc add @sentry/react-native
```
Comment (AbhiPrasad) [inline .github/workflows/e2e.yml:44]: Think its unavoidable now, but lets please split up the CI changes from the implementation so that things are easier to revert/`git blame` in the future.

File: sample/android/app/src/main/java/io/sentry/sample/MainApplication.java [hunk 8]
```diff
@@ -25,7 +25,19 @@ public boolean getUseDeveloperSupport() {
     protected List<ReactPackage> getPackages() {
       @SuppressWarnings("UnnecessaryLocalVariable")
       List<ReactPackage> packages = new PackageList(this).getPackages();
-      packages.add(new RNSentryPackage());
+
+      boolean packageExists = false;
+      for (ReactPackage pkg : packages) {
+        if (pkg instanceof RNSentryPackage) {
+          packageExists = true;
```
Comment (AbhiPrasad) [inline sample/android/app/src/main/java/io/sentry/sample/MainApplication.java:32]: can we just do an early return here instead of the mutable flag?

File: src/js/integrations/reactnativeerrorhandlers.ts (hunk 5 above)
Comment (AbhiPrasad) [inline src/js/integrations/reactnativeerrorhandlers.ts:83]: Let's please extract setting `promiseRejectionTrackingOptions` into a function and then always return a const. The require check is an implementation detail that `_handleUnhandledRejections` shouldn't have to worry about imo.

**Review by AbhiPrasad — CHANGES_REQUESTED** [review]
awesome, sorry for the late review. I'll make sure the ✅ comes back way faster :)))

**Comment by jennmueng** [comment]
Thanks @AbhiPrasad! Just got back from thanksgiving break and addressed your review. Next time will make separate PRs for CI changes.

**Review by marandaneto — APPROVED** [review]

File: src/js/integrations/reactnativeerrorhandlers.ts [hunk 9]
```diff
@@ -51,66 +57,88 @@ export class ReactNativeErrorHandlers implements Integration {
...
-      /* eslint-disable
-        @typescript-eslint/no-var-requires,
-        import/no-extraneous-dependencies,
-        @typescript-eslint/no-explicit-any,
-        @typescript-eslint/no-unsafe-member-access
-      */
+    try {
+      // Here we try to use React Native's original promise rejection handler.
+      // eslint-disable-next-line @typescript-eslint/no-var-requires,@typescript-eslint/no-unsafe-member-access
+      promiseRejectionTrackingOptions = require("react-native/Libraries/promiseRejectionTrackingOptions")
```
Comment (AbhiPrasad) [inline src/js/integrations/reactnativeerrorhandlers.ts:112]: Can’t we just return here?

**Review by AbhiPrasad — APPROVED** [review]

File: .github/workflows/e2e.yml (hunk 7 above)
Comment (marandaneto) [reply .github/workflows/e2e.yml:44]: agreed, but splitting up would break the e2e since the CI changes are needed, let's keep this in mind for the next PR but I'd rather merge it for now since it's an important fix.

**Comment by marandaneto** [comment]
thanks for reviewing @AbhiPrasad
