### PR TITLE
Fix: Implement fallback system to screens that aren't reporting on the native layer the time to display.

### LINKED ISSUE #3934: Manual TTID/TTFD API times out
**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

```
export const routingInstrumentation = new Sentry.ReactNavigationInstrumentation(
  {
    enableTimeToInitialDisplay: true,
  },
);


Sentry.init({
  environment: 'development'
  sampleRate: 1.0,
  tracesSampleRate: 0.1,
  enableAppHangTracking: false,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
      tracePropagationTargets: [currentConfig.DOMAIN],
    }),
  ],
});
```
---
**I have the following issue:**

I am seeing some inconsistencies in the data reported and what should be reported based on the SDK behaviour. For example, it is odd to me that some transactions are being marked as '***deadline_exceeded***' when they do not exceed the default value for [[finalTimeoutMs](https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/reactnativetracing.ts#L61)]. `finalTimeoutMs` is also not being overridden in the init code block

The default for `finalTimeoutMs` is 600000ms or 10mins, which is way above what the transactions being marked deadline_exceeded are reporting. The amount of failed transactions with this status seems to have increased after updating the SDK version from `5.3.0` to `5.22.0`

More details with links to examples in the [Customer Case](https://www.notion.so/sentry/Increase-in-deadline_exceeded-after-upgrade-9d472c310520417eb9ed4ab72a554dcc?pvs=4)

### PR DESCRIPTION
**Pull request by lucas-zimerman**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Context: the current native implementation doesn't always emit the required event in order to track the required time to display to be set on the time to display span. 

To fix that, I introduced an additional fallback emitter, in short, it reuses the same flow by emitting the original [event](https://github.com/getsentry/sentry-react-native/pull/4042/files#diff-2b6b8eb3a7668d3a9f076a37f76f1b330c5c4219ab8c08afa5ed4c9609535a76R61) when the fallback emitter received the notification that the page was rendered and the original emitter didn't emit any event on the following 3 seconds.

With those changes, we have the following benefits:
- Support for React Native web by also having the JavaScript fallback of [requestAnimationFrame](https://reactnative.dev/docs/timers).
- Greatly reduces the wrong time to display end timestamp by having a fallback when the original implementation doesn't return any event.
- Fallback to the JavaScript implementation in case both Native emitters fail.

## :bulb: Motivation and Context

Close #3934, https://github.com/getsentry/sentry-react-native/issues/3809

## :green_heart: How did you test it?

The playground tab on our sample is a good case for testing, since it doesn't use navigation stack on it, the events on this condition are limited, not generating and required event by us in order to track the time to display.

I used it and other tabs to compare the difference between the original implementation and also `requestAnimationFrame`, and the time difference between each other was quite low:

1St Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293664.8300002
Original: InitAsync Event received {"newFrameTimestampInSeconds":1724293664.8179998}

2Nd Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293761.688
Original: InitAsync Event received {"newFrameTimestampInSeconds":1724293761.689}

3Rd Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293824.887
Original: Android didn't emit an event for this page so it wasn't measured

Before this change on the playground screen:
https://sentry-sdks.sentry.io/performance/trace/10bd4bf28052404592f408f3cf58175a/?dataset=transactions&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&fov=0%2C15046.88916015625&id=21705&name=&node=trace-root&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1724358725&topEvents=5&yAxis=count%28%29

After this change on the playground screen:
https://sentry-sdks.sentry.io/performance/trace/8cb478b4370e444fa4a7b9be778d51ab/?dataset=transactions&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&fov=0%2C235&id=21705&name=&node=txn-b5a8ba18aa254fe79743133baf9071b2&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1724359145&topEvents=5&yAxis=count%28%29

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by krystofwoldrich** [comment]
Hi @lucas-zimerman,
thank you for the detailed description, and opening the draft PR, this makes validation and discussing the ideas much easier.

I think waiting for the next drawn frame is a good fallback. But there is one party breaker hidden in the RN implementation. Compared to browsers implementation, in RN `requestAnimationFrame` is the same as `setTimeout(timeout, 0)`.

This means the callback runs after the React Native Node Tree is assembled and passed to native. So unless the JS loop is doing some heavy task, it will generally be executed before the render.

We can fix that by implementing our own `requestAnimationFrame` which will emit an event from the native layer when the next frame is rendered.

```
onNavigationStateChanged() {
  // executed in useEffect of the root navigator 
  SENTRY_NATIVE.requestAnimationFrame((frameTimestamp) {
  	// this will actually be called on the next native frame (linked to main app thread)
  })
}
```

```
// NATIVE IMPL
SENTRY_NATIVE.requestAnimationFrame(callback) {
	// Similar to RNSentryOnDrawReporterView implementation
	// https://github.com/getsentry/sentry-react-native/blob/cc9666e872837955125bd0a80492e57625fc16a0/android/src/main/java/io/sentry/react/RNSentryOnDrawReporterManager.java#L121
	// https://github.com/getsentry/sentry-react-native/blob/2b83fc5d3de33c5eab1c8a08d762ac813e3a7c9b/ios/RNSentryOnDrawReporter.m#L44
	hookToNextFrame(() {
		callback(Date.now())
	})
}
```

The native implementation would the same method to hook into the render loop as RNSentryOnDrawReporterView but instead of component it would be native method of RNSentry.

I think we can still use the JS `requestAnimationFrame` to add support to `react-native-web` and maybe good fall back for `Expo Go`. 

It should work well with the current draft, replacing `requestAnimationFrame` with custom method.

Let me know what you think, if my though process make sense, or I've missed something.

File: samples/react-native/src/Screens/PerformanceScreen.tsx [hunk 1]
```diff
@@ -62,6 +72,787 @@ const PerformanceScreen = (props: Props) => {
...
+  title="Redux Example"
+  onPress={() => {
+    props.navigation.navigate('Redux');
+  }}
+/>        <Button
+          title="Redux Example"
+          onPress={() => {
+            props.navigation.navigate('Redux');
+          }}
+        />
```
Comment (lucas-zimerman) [inline samples/react-native/src/Screens/PerformanceScreen.tsx:855]:
```suggestion
```

File: samples/react-native/src/Screens/PerformanceScreen.tsx [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import React from 'react';
+import React, { useEffect, useState } from 'react';
```
Comment (lucas-zimerman) [inline samples/react-native/src/Screens/PerformanceScreen.tsx:1]:
```suggestion
import React from 'react';
```

File: samples/react-native/src/Screens/PerformanceScreen.tsx [hunk 3]
```diff
@@ -32,6 +32,16 @@ const PerformanceScreen = (props: Props) => {
...
+  const [isLoading, setIsLoading] = useState(true);
+  useEffect(() => {
+    // Simulate heavy computation for 5 seconds
+    const start = Date.now();
+    while (Date.now() - start < 5000) {
+      // Perform some meaningless computation to occupy the CPU
+      Math.sqrt(Math.random() * Math.random());
+    }
+    setIsLoading(false);
+  }, []);
```
Comment (lucas-zimerman) [inline samples/react-native/src/Screens/PerformanceScreen.tsx:44]:
```suggestion
```

**Comment by lucas-zimerman** [comment]
iOS integration should also be done and tests are also completed.

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java [hunk 4]
```diff
@@ -135,10 +135,16 @@ public class RNSentryModuleImpl {
     /** Max trace file size in bytes. */
     private long maxTraceFileSize = 5 * 1024 * 1024;
 
+
+
+  private final RNSentryTimeToDisplay timeToDisplay;
+
+
```
Comment (lucas-zimerman) [inline android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:142]:
```suggestion
  private final RNSentryTimeToDisplay timeToDisplay;
```

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java [hunk 5]
```diff
@@ -1,5 +1,5 @@
 package io.sentry.react;
-
+import android.view.Choreographer;
```
Comment (lucas-zimerman) [inline android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:2]:
```suggestion

import android.view.Choreographer;
```

File: android/src/main/java/io/sentry/react/RNSentryPackage.java [hunk 6]
```diff
@@ -20,9 +20,9 @@ public class RNSentryPackage extends TurboReactPackage {
   @Nullable
   @Override
   public NativeModule getModule(String name, ReactApplicationContext reactContext) {
-    if (name.equals(RNSentryModuleImpl.NAME)) {
-      return new RNSentryModule(reactContext);
-    } else {
+      if (name.equals(RNSentryModuleImpl.NAME)) {
+        return new RNSentryModule(reactContext);
+      } else {
```
Comment (lucas-zimerman) [inline android/src/main/java/io/sentry/react/RNSentryPackage.java:25]:
```suggestion
    if (name.equals(RNSentryModuleImpl.NAME)) {
      return new RNSentryModule(reactContext);
    } else {
```

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+import android.view.Choreographer;
+
+import androidx.annotation.NonNull;
+
+import org.jetbrains.annotations.NotNull;
+import io.sentry.SentryDate;
+import io.sentry.SentryDateProvider;
+import io.sentry.android.core.SentryAndroidDateProvider;
+
+
```
Comment (lucas-zimerman) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:18]:
```suggestion
```

File: ios/RNSentry.mm [hunk 8]
```diff
@@ -776,4 +780,10 @@ - (NSDictionary*) fetchNativeStackFramesBy: (NSArray<NSNumber*>*)instructionsAdd
 }
 #endif
 
+RCT_EXPORT_METHOD(getNewScreenTimeToDisplay:(RCTPromiseResolveBlock)resolve
+                  rejecter:(RCTPromiseRejectBlock)reject) {
+  [_timeToDisplay getTimeToDisplay:resolve];
+}
+
+
```
Comment (lucas-zimerman) [inline ios/RNSentry.mm:788]:
```suggestion
```

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java [hunk 9]
```diff
@@ -1,5 +1,6 @@
 package io.sentry.react;
 
+import android.view.Choreographer;
```
Comment (antonis) [inline android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:3]: I think it is safe to remove this import since the class is only used inside the `RNSentryTimeToDisplay` implementation.
```suggestion
```

Comment (antonis) [reply android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:3]: I've also noticed a few more imports unrelated with this PR that can be safely removed. I'm attaching a patch since it escapes the scope GH allows me to comment on. I can handle this on a separate PR if it is more proper.
[imports.patch](https://github.com/user-attachments/files/17113794/imports.patch)

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java [hunk 10]
```diff
@@ -135,10 +136,12 @@ public class RNSentryModuleImpl {
     /** Max trace file size in bytes. */
     private long maxTraceFileSize = 5 * 1024 * 1024;
 
+  private final RNSentryTimeToDisplay timeToDisplay;
```
Comment (antonis) [inline android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:139]: `l`: Minor formating nitpick
```suggestion
     private final RNSentryTimeToDisplay timeToDisplay;
     
```

File: android/src/newarch/java/io/sentry/react/RNSentryModule.java [hunk 11]
```diff
@@ -173,4 +173,9 @@ public String getCurrentReplayId() {
     public void crashedLastRun(Promise promise) {
         this.impl.crashedLastRun(promise);
     }
+
+      @Override
+     public void getNewScreenTimeToDisplay(Promise promise) {
+        this.impl.getNewScreenTimeToDisplay(promise);
+     }
```
Comment (antonis) [inline android/src/newarch/java/io/sentry/react/RNSentryModule.java:180]: `l`: Minor formating nitpick
```suggestion
    @Override
    public void getNewScreenTimeToDisplay(Promise promise) {
        this.impl.getNewScreenTimeToDisplay(promise);
    }
```

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 12]
```diff
@@ -0,0 +1,35 @@
+package io.sentry.react;
+
+import com.facebook.react.bridge.ReactContextBaseJavaModule;
+import com.facebook.react.bridge.ReactApplicationContext;
+import com.facebook.react.bridge.ReactMethod;
+import com.facebook.react.bridge.Promise;
+import com.facebook.react.turbomodule.core.interfaces.TurboModule;
+
+import android.view.Choreographer;
```
Comment (antonis) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:9]: `l`: We could remove the unused imports
```suggestion
import com.facebook.react.bridge.Promise;

import android.view.Choreographer;
```

File: ios/RNSentry.mm [hunk 13]
```diff
@@ -1,5 +1,6 @@
 #import <dlfcn.h>
 #import "RNSentry.h"
+#import  "RNSentryTimeToDisplay.h"
```
Comment (antonis) [inline ios/RNSentry.mm:3]: `l`: Minor code formatting
```suggestion
#import "RNSentryTimeToDisplay.h"
```

File: ios/RNSentry.mm [hunk 14]
```diff
@@ -776,4 +780,9 @@ - (NSDictionary*) fetchNativeStackFramesBy: (NSArray<NSNumber*>*)instructionsAdd
 }
 #endif
 
+RCT_EXPORT_METHOD(getNewScreenTimeToDisplay:(RCTPromiseResolveBlock)resolve
+                  rejecter:(RCTPromiseRejectBlock)reject) {
+  [_timeToDisplay getTimeToDisplay:resolve];
```
Comment (antonis) [inline ios/RNSentry.mm:785]: `l`: Minor code formatting
```suggestion
    [_timeToDisplay getTimeToDisplay:resolve];
```

File: ios/RNSentryTimeToDisplay.m [hunk 15]
```diff
@@ -0,0 +1,43 @@
+#import "RNSentryTimeToDisplay.h"
+#import <QuartzCore/QuartzCore.h>
+#import <React/RCTLog.h>
+
+@implementation RNSentryTimeToDisplay
```
Comment (antonis) [inline ios/RNSentryTimeToDisplay.m:5]: Q: I wonder if we could reuse the implementation of [`SentryDisplayLinkWrapper`](https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/include/SentryDisplayLinkWrapper.m) on this class.

**Review by antonis — APPROVED** [review]
Awesome work @lucas-zimerman!
LGTM! I've left some suggestions/comments on the native side mainly related to formatting.
Thank you for also adding extensive test cases 🙇

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java (hunk 9 above)
Comment (lucas-zimerman) [reply android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:3]: Thank you for checking this!
Would you mind making another PR for the other unused imports? (this way you also get another PR here hehe)

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 16]
```diff
@@ -0,0 +1,29 @@
...
+
+        // Invoke the callback after the frame is rendered
+        choreographer.postFrameCallback(frameTimeNanos -> {
+                final @NotNull SentryDateProvider dateProvider = new SentryAndroidDateProvider();
+
+                final SentryDate endDate = dateProvider.now();
+
+                promise.resolve(endDate.nanoTimestamp() / 1e9);
+            }
+        });
```
[the remark this answers is not in the document]
Comment (lucas-zimerman) [reply android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:26]: ah no worries, thanks for the checking it :D

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java (hunk 9 above)
Comment (antonis) [reply android/src/main/java/io/sentry/react/RNSentryModuleImpl.java]: > Would you mind making another PR for the other unused imports? (this way you also get another PR here hehe)

@lucas-zimerman Closing the loop here I've opened a PR at https://github.com/getsentry/sentry-react-native/pull/4119
Feel free to merge on top of your PR or after your PR is merged.

**Comment by lucas-zimerman** [comment]
@stefanosiano or @brustolin could you guys help to review the native code?

File: ios/RNSentryTimeToDisplay.m (hunk 15 above)
Comment (brustolin) [reply ios/RNSentryTimeToDisplay.m:5]: SentryDisplayLinkWrapper is not available for RN, we could do it, but I think this Is good enough.

Comment (antonis) [reply ios/RNSentryTimeToDisplay.m:5]: Makes sense 👍 Thank you for your response 🙇

**Review by brustolin — APPROVED** [review]
The objc code looks good to me. I did not review the rest.

File: android/src/main/java/io/sentry/react/RNSentryModuleImpl.java [hunk 17]
```diff
@@ -135,10 +131,13 @@ public class RNSentryModuleImpl {
     /** Max trace file size in bytes. */
     private long maxTraceFileSize = 5 * 1024 * 1024;
 
+     private final RNSentryTimeToDisplay timeToDisplay;
```
Comment (krystofwoldrich) [inline android/src/main/java/io/sentry/react/RNSentryModuleImpl.java:134]:
```suggestion
    private final RNSentryTimeToDisplay timeToDisplay;
```

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 18]
```diff
@@ -0,0 +1,26 @@
...
+import io.sentry.android.core.SentryAndroidDateProvider;
+
+public class RNSentryTimeToDisplay {
+
+    public void GetTimeToDisplay(Promise promise) {
+        Choreographer choreographer = Choreographer.getInstance();
+
+        // Invoke the callback after the frame is rendered
+        choreographer.postFrameCallback(frameTimeNanos -> {
+                final @NotNull SentryDateProvider dateProvider = new SentryAndroidDateProvider();
```
Comment (krystofwoldrich) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:19]: Can we reuse the `dateProvider`, maybe even share it with the main Impl.

So we avoid creating it on every call.

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 19]
```diff
@@ -0,0 +1,26 @@
...
+import android.view.Choreographer;
+
+import org.jetbrains.annotations.NotNull;
+import io.sentry.SentryDate;
+import io.sentry.SentryDateProvider;
+import io.sentry.android.core.SentryAndroidDateProvider;
+
+public class RNSentryTimeToDisplay {
+
+    public void GetTimeToDisplay(Promise promise) {
```
Comment (krystofwoldrich) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:14]: Since we don't have any state, this could be a static function, getting the promise and dataProvider in arguments.

File: src/js/utils/sentryeventemitterfallback.ts [hunk 20]
```diff
@@ -0,0 +1,103 @@
...
+
+  function defaultFallbackEventEmitter(): void {
+    // Schedule the callback to be executed when all UI Frames have flushed.
+    requestAnimationFrame(() => {
+      if (NativeEmitterCalled) {
+        NativeEmitterCalled = false;
+        isListening = false;
+        return;
+      }
+      const timestampInSeconds = timeNowNanosecond();
```
Comment (krystofwoldrich) [inline src/js/utils/sentryeventemitterfallback.ts:39]: Let's use `timestampInSeconds` from `@sentry/utils`. It uses more precise and monotonic clock.

File: src/js/utils/sentryeventemitterfallback.ts [hunk 21]
```diff
@@ -0,0 +1,103 @@
...
+ * Creates emitter that allows to listen to UI Frame events when ready.
+ */
+export function createSentryFallbackEventEmitter(): SentryEventEmitterFallback {
+  let NativeEmitterCalled: boolean = false;
+  let subscription: EmitterSubscription | undefined = undefined;
+  let isListening = false;
+
+  function defaultFallbackEventEmitter(): void {
+    // Schedule the callback to be executed when all UI Frames have flushed.
+    requestAnimationFrame(() => {
```
Comment (krystofwoldrich) [inline src/js/utils/sentryeventemitterfallback.ts:33]: We should include here link to the RN explanation and also mentioned that currently its not the measuring the UI frames but it's implemented as `setTimeout(() => {}, 0)`

File: src/js/utils/sentryeventemitterfallback.ts [hunk 22]
```diff
@@ -0,0 +1,103 @@
...
+      const timestampInSeconds = timeNowNanosecond();
+      waitForNativeResponseOrFallback(timestampInSeconds, 'JavaScript');
+    });
+  }
+
+  function waitForNativeResponseOrFallback(fallbackSeconds: number, origin: string): void {
+    const maxRetries = 3;
+    let retries = 0;
+
+    const retryCheck = (): void => {
```
Comment (krystofwoldrich) [inline src/js/utils/sentryeventemitterfallback.ts:48]: Can we replace the retry with one 3s timeout (have I missed why we use the retry)?

If the new frame event is emitted correctly we can use `clearTimeout`.

File: src/js/tracing/reactnavigation.ts [hunk 23]
```diff
@@ -101,7 +102,9 @@ export class ReactNavigationInstrumentation extends InternalRoutingInstrumentati
 
     if (this._options.enableTimeToInitialDisplay) {
       this._newScreenFrameEventEmitter = createSentryEventEmitter();
+      this._newFallbackEventEmitter = createSentryFallbackEventEmitter();
```
Comment (krystofwoldrich) [inline src/js/tracing/reactnavigation.ts:105]: I think `sentryEventEmitter` could be internally used in the `sentryFallbackEventEmitter`. To isolate the fallback logic and remove it from ReactNavigation.

File: src/js/utils/sentryeventemitterfallback.ts [hunk 24]
```diff
@@ -0,0 +1,103 @@
...
+        if (isListening) {
+          NativeEmitterCalled = true;
+        }
+      });
+    },
+
+    startListenerAsync() {
+      isListening = true;
+
+      NATIVE.getNewScreenTimeToDisplay()
```
Comment (krystofwoldrich) [inline src/js/utils/sentryeventemitterfallback.ts:85]: I think the timeout should start here and if the none of the new display time to displays (not react nav, not native fallback, not JS fallback) was retried it should just log error., otherwise it's 3s + the time of NewScreeTimeToDisplay.

File: test/utils/sentryeventemitterfallback.test.ts [hunk 25]
```diff
@@ -0,0 +1,241 @@
...
+
+  it('should start listener and use fallback when native call returned undefined/null', async () => {
+    jest.useFakeTimers();
+    const fallbackTime = Date.now() / 1000;
+
+    const animation = NATIVE.getNewScreenTimeToDisplay as jest.Mock;
+    animation.mockReturnValue(Promise.resolve());
+
+    emitter.startListenerAsync();
+    await animation; // wait for the Native execution to be completed.
```
Comment (krystofwoldrich) [inline test/utils/sentryeventemitterfallback.test.ts:67]: The current `await animation` allows the next event loop, but doesn't wait for the execution to be completed. I would rename this to be more accurate, but the test works correct in both cases.

```suggestions
    (NATIVE.getNewScreenTimeToDisplay as jest.Mock).mockReturnValue(Promise.resolve());

    emitter.startListenerAsync();

    // Wait for the next event loop to allow startListenerAsync to call NATIVE.getNewScreenTimeToDisplay
    await Promise.resolve();
```

**Comment by krystofwoldrich** [comment]
The PR is looking good, but I have some questions about the fallbacks timing and some small refactoring ideas.

File: test/utils/sentryeventemitterfallback.test.ts (hunk 25 above)
Comment (lucas-zimerman) [reply test/utils/sentryeventemitterfallback.test.ts:67]: Thank you for the suggestion! I will apply it to the other tests too.

File: src/js/utils/sentryeventemitterfallback.ts [hunk 26]
```diff
@@ -0,0 +1,103 @@
...
+            defaultFallbackEventEmitter();
+          }
+        })
+        .catch((reason: Error) => {
+          logger.error('Failed to recceive Native fallback timestamp.', reason);
+          defaultFallbackEventEmitter();
+        });
+    },
+
+    closeAll() {
```
[the remark this answers is not in the document]
Comment (lucas-zimerman) [reply src/js/utils/sentryeventemitterfallback.ts:99]: Should we also remove the `closeAll` on `sentryeventemitter`? It seems not used too.

File: src/js/utils/sentryeventemitterfallback.ts (hunk 22 above)
Comment (lucas-zimerman) [reply src/js/utils/sentryeventemitterfallback.ts:48]: One retry with 3s also works too

File: src/js/tracing/reactnavigation.ts (hunk 23 above)
Comment (lucas-zimerman) [reply src/js/tracing/reactnavigation.ts:105]: I think you want to move the fallback inside of sentryEventEmitter? if so, I moved it.

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java (hunk 19 above)
Comment (lucas-zimerman) [reply android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:14]: Also made `createEmitNewFrameEvent` to use the shared dateProvider

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 27]
```diff
@@ -0,0 +1,23 @@
...
+import android.view.Choreographer;
+
+import org.jetbrains.annotations.NotNull;
+import io.sentry.SentryDate;
+import io.sentry.SentryDateProvider;
+import io.sentry.android.core.SentryAndroidDateProvider;
+
+public class RNSentryTimeToDisplay {
+    public static void GetTimeToDisplay(Promise promise, SentryDateProvider dateProvider) {
+        Choreographer choreographer = Choreographer.getInstance();
```
Comment (stefanosiano) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:14]: Shouldn't it be in a try catch block?
accessing Choreographer may result in an exception (we had some reports in the SDK console)

File: src/js/utils/sentryeventemitterfallback.ts (hunk 26 above)
[the remark this answers is not in the document]
Comment (krystofwoldrich) [reply src/js/utils/sentryeventemitterfallback.ts]: Yes, we can clean that up, after the fallback. I agree.

File: src/js/tracing/reactnavigation.ts (hunk 23 above)
Comment (krystofwoldrich) [reply src/js/tracing/reactnavigation.ts]: I was thinking about something like this: https://github.com/getsentry/sentry-react-native/compare/test/deadline...kw-fallback-emitter-suggestion

Using the `sentryEventEmitter` inside of `sentryFallbackEventEmitter` and than use the `sentryFallbackEventEmitter` in `reactnavigation`.

Let me know what do you think about the suggestion.

File: android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java [hunk 28]
```diff
@@ -0,0 +1,28 @@
...
+
+import org.jetbrains.annotations.NotNull;
+import io.sentry.SentryDate;
+import io.sentry.SentryDateProvider;
+import io.sentry.android.core.SentryAndroidDateProvider;
+
+public class RNSentryTimeToDisplay {
+    public static void GetTimeToDisplay(Promise promise, SentryDateProvider dateProvider) {
+        try {
+            Choreographer choreographer = Choreographer.getInstance();
```
Comment (krystofwoldrich) [inline android/src/main/java/io/sentry/react/RNSentryTimeToDisplay.java:15]: We should run the `Choreographer.getInstance()` on the Main Thread as this function returns instance for the current thread.

https://github.com/getsentry/sentry-java/blob/b11dc55cfc01379e481be60de78b512191128a25/sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java#L121
https://developer.android.com/reference/android/view/Choreographer#getInstance()

**Comment by krystofwoldrich** [comment]
Thank you @lucas-zimerman, it's looking good. 

I've noticed one last thing with the choreographer. See https://github.com/getsentry/sentry-react-native/pull/4042#discussion_r1800711808

**Comment by krystofwoldrich** [comment]
I've changed the target to `v5` to avoid conflicts.

But we should include this also in version 6.

First we release it as beta on v5 and then also as a hotfix on `6.0.1`

**Review by krystofwoldrich — APPROVED** [review]
Thank you! @lucas-zimerman 

Large improvement for TTD.

**Comment by krystofwoldrich** [comment]
@lucas-zimerman 

Can you port this also to v6 (main)?

**Comment by lucas-zimerman** [comment]
Sure thing, I will port it to V6
