### PR TITLE
fix(core): Defer initial navigation span creation until navigation container is registered

### LINKED ISSUE #4788: Profiling and Mobile Vitals (insights) not working on latest version of react native sdk
### What React Native libraries do you use?

React Native without Frameworks, React Navigation, Hermes, RN New Architecture

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.10.0

### How does your development environment look like?

````
System:
  OS: macOS 15.4
  CPU: (12) arm64 Apple M2 Pro
  Memory: 273.41 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.asdf/installs/nodejs/20.17.0/bin/node
  Yarn: Not Found
  npm:
    version: 11.3.0
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2025.03.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/ricardosanchez/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "28"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
      - 34.0.0
      - 34.0.0
      - 35.0.0
      - 35.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.22562.218.2431.13114758
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/ricardosanchez/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: ^15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.7
    wanted: ^0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

info React Native v0.79.1 is now available (your project is running on v0.76.7).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.79.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.7&to=0.79.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".




````

### Sentry.init()

````js

  const navigationIntegration = Sentry.reactNavigationIntegration({
    enableTimeToInitialDisplay: true,
  })

  // Sentry integrations
  const mobileReplayIntegration = Sentry.mobileReplayIntegration({
    maskAllText: false,
  })

    Sentry.init({
      dsn: currentConfig.sentry.dsn,
      environment: currentEnvironment,
      tracesSampleRate: 1.0,
      profilesSampleRate: 1.0,
      replaysSessionSampleRate: 1.0,
      replaysOnErrorSampleRate: 1.0,
      integrations: [
        Sentry.reactNativeTracingIntegration(),
        mobileReplayIntegration,
        navigationIntegration,
      ],
    })
````

### Steps to Reproduce

1. Add sentry init as mentioned above
2. add the following to `'@react-navigation/native'` 's `<NaviogationContainer>`:

- `navigationIntegration.registerNavigationContainer(NAVIGATION_REF)`

3. Install the app on physical devices
4. Replays and general errors are working as expected
5. Expects vitals and profiling info on Sentry Dashboard

### Expected Result

Mobile vitals should be send to Sentry Dashboard, as for testing we are setting the `tracesSampleRate` and `profilesSampleRate`, `replaysSessionSampleRate`, and `replaysOnErrorSampleRate` to 1.0.

### Actual Result

- Only Replays and general error are being reportes

### PR DESCRIPTION
**Pull request by antonis**
## :loudspeaker: Type of change
- [x] Bugfix

## :scroll: Description

Defers the initial navigation span creation from `afterAllSetup` to `registerNavigationContainer` when the navigation container is not yet available.

Previously, `afterAllSetup` unconditionally called `startIdleNavigationSpan()`, which started a 1-second idle timeout and a 1-second discard timeout. If `registerNavigationContainer` (called from `NavigationContainer.onReady`) wasn't invoked within that window, the span was discarded — taking app start data and mobile vitals with it.

Now:
- `afterAllSetup` only creates the span if the container is already registered (e.g. test setup pattern)
- `registerNavigationContainer` creates the span if `afterAllSetup` has already run but no span exists yet (production pattern)
- An `isSetupComplete` flag coordinates between the two functions to handle both orderings

## :bulb: Motivation and Context

Fixes #4788

Users reported that mobile vitals and `ui.load` spans were not being captured, with debug logs showing "Discarding transaction because its trace was not chosen to be sampled". A potential cause is a race condition: the initial navigation span's idle/discard timeouts (both 1s) fire before the navigation container registers and populates the span with route info.

## :green_heart: How did you test it?

- All existing tests pass (1069 tests)
- Added 5 new tests in `deferred initial span creation` covering:
  - Production flow: init → registerNavigationContainer creates span
  - Delayed registration (500ms) still creates span successfully
  - `afterAllSetup` without container creates no span
  - Subsequent navigations work after deferred initial span
  - `runApplication` callbacks work after deferred initial state

## :pencil: Checklist
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

### CODE REVIEW

File: packages/core/src/js/tracing/reactnavigation.ts [hunk 1]
```diff
@@ -282,8 +284,11 @@ export const reactNavigationIntegration = ({
     }
 
     if (!latestNavigationSpan) {
-      debug.log(`${INTEGRATION_NAME} Navigation container registered, but integration has not been setup yet.`);
-      return undefined;
+      if (!isSetupComplete) {
+        debug.log(`${INTEGRATION_NAME} Navigation container registered, but integration has not been setup yet.`);
```
Comment (lucas-zimerman) [inline packages/core/src/js/tracing/reactnavigation.ts]: Nit: What do you think on this message update to end users?
```suggestion
        debug.log(`${INTEGRATION_NAME} Navigation container registered before integration setup. Initial span will be created when setup completes.`);
```
