### PR TITLE
expo-upload-sourcemaps now works on Windows

### LINKED ISSUE #3613: [Expo SDK50] npx sentry-expo-upload-sourcemaps dist throws error, sentry-cli is not recognized as an internal or external command
**OS:**
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.4

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    enabled: !__DEV__, 
    debug: false 
  });
```

---
**I have the following issue:**

`npx sentry-expo-upload-sourcemaps dist` returns below error
```
⬆️ Uploading dist\_expo\static\js\ios\index-***.hbc bundle and sourcemap...
'D:\***\***\node_modules\@sentry\cli\bin\sentry-cli' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:965
    throw err;
    ^

Error: Command failed: D:\***\***\node_modules\@sentry\cli\bin\sentry-cli sourcemaps upload --debug-id-reference dist\_expo\static\js\ios\index-***.hbc dist\_expo\static\js\ios\index-***.hbc.map
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (D:\***\***\node_modules\@sentry\react-native\scripts\expo-upload-sourcemaps.js:151:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18904,
  stdout: null,
  stderr: null
}

Node.js v21.6.2

```

**Steps to reproduce:**
1. Run `eas update --branch production --platform ios` to produce new sourcemaps in dist folder
2. Run `npx sentry-expo-upload-sourcemaps dist`

- Installed using `npx expo install @sentry/react-native` version 5.17.0.
- Tried updating @sentry/react-native to version 5.19.0, same error.
- `eas build` automatic sourcemaps upload is working fine

**Actual result:**

```
⬆️ Uploading dist\_expo\static\js\ios\index-***.hbc bundle and sourcemap...
'D:\***\***\node_modules\@sentry\cli\bin\sentry-cli' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:965
    throw err;
    ^

Error: Command failed: D:\***\***\node_modules\@sentry\cli\bin\sentry-cli sourcemaps upload --debug-id-reference dist\_expo\static\js\ios\index-***.hbc dist\_expo\static\js\ios\index-***.hbc.map
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (D:\***\***\node_modules\@sentry\react-native\scripts\expo-upload-sourcemaps.js:151:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18904,
  stdout: null,
  stderr: null
}

Node.js v21.6.2

```

**Expected result:**

New sourcemaps successfully updated to sentry.io

### PR DESCRIPTION
**Pull request by lucas-zimerman**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

when on Windows, the execution will call "node sentry-cli..."  which will behave the same as on MacOS and Linux.
The main difference is that only calling "sentry-cli ..." on a Unix system works is due to the first line on the file telling the shell to invoke the file with the Node cli. 

## :bulb: Motivation and Context

It makes the script usable on Windows.
Fixes #3613

## :green_heart: How did you test it?

Localy on a  brand new project invoking the script the same way as users did, the below script shows sentry cli being invoked on a Windows device where previously it wouldn't execute it.
```
⬆️ Uploading dist\_expo\static\js\web\AppEntry-f904ff768b6e71e8cc866a59c8a999de1.js bundle and sourcemap...
> Found 1 file                                                             
> Found 1 file                                                             
> Analyzing 2 sources
> Analyzing completed in 0.01s
> Rewriting sources
> Rewriting completed in 0.07s
> Adding source map references
error: This version of Sentry does not support artifact bundles. A release slug is required (provide with --release)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

Command failed, however, "SENTRY_ALLOW_FAILURE" variable or "allow-failure" flag was set. Exiting with 0 exit code.
✅ Uploaded bundles and sourcemaps to Sentry successfully.
```

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: scripts/expo-upload-sourcemaps.js [hunk 1]
```diff
@@ -195,8 +196,7 @@ if (numAssetsUploaded === totalAssets) {
   console.log('✅ Uploaded bundles and sourcemaps to Sentry successfully.');
 } else {
   console.warn(
-    `⚠️  Uploaded ${numAssetsUploaded} of ${totalAssets} bundles and sourcemaps. ${
-      numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''
+    `⚠️  Uploaded ${numAssetsUploaded} of ${totalAssets} bundles and sourcemaps. ${numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''
```
Comment (lucas-zimerman) [inline scripts/expo-upload-sourcemaps.js:199]:
```suggestion
    `⚠️  Uploaded ${numAssetsUploaded} of ${totalAssets} bundles and sourcemaps. ${
      numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''```

File: scripts/expo-upload-sourcemaps.js [hunk 2]
```diff
@@ -196,7 +197,7 @@ if (numAssetsUploaded === totalAssets) {
 } else {
   console.warn(
     `⚠️  Uploaded ${numAssetsUploaded} of ${totalAssets} bundles and sourcemaps. ${
-      numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''
+      numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''```
```
Comment (lucas-zimerman) [inline scripts/expo-upload-sourcemaps.js:200]:
```suggestion
      numAssetsUploaded === 0 ? 'Ensure you are running `expo export` with the `--dump-sourcemap` flag.' : ''
```

**Review by krystofwoldrich — APPROVED** [review]
LGTM 🚀 Thank you!
