### PR TITLE
fix: Debugsymbolicator

### LINKED ISSUE #846: prettyStack.filter is not a function
OS:
- [ ]  Windows
- [ ]  MacOS
- [ X ]  Linux

Platform:
- [X ]  iOS
- [ X]  Android

SDK:
- [ X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.62.2

Are you using Expo?
- [ ]  Yes
- [X ]  No

Are you using sentry.io or on-premise?
- [X ]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```javascript
Sentry.init({
  dsn: 'MY DSN', 
  debug: true,
  environment: 'development',
});
```

---
I have following issue:
When I run my app, I receive this warning:
```javascript
Sentry Logger [Warn]: Unable to symbolicate stack trace: prettyStack.filter is not a function
```

**Steps to reproduce:**
- Just initials your sentry as above

**Actual result:**
```javascript
Sentry Logger [Warn]: Unable to symbolicate stack trace: prettyStack.filter is not a function
```

**Expected result:**
I should not get any warnings

### PR DESCRIPTION
**Pull request by HazAT**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Fix a bug in DebugSymbolicator Integration
image

Also fixed loading local js from for sample project

Fixes #846

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing

### CODE REVIEW

File: src/js/integrations/debugsymbolicator.ts [hunk 1]
```diff
@@ -86,8 +87,14 @@ export class DebugSymbolicator implements Integration {
...
       const symbolicateStackTrace = require("react-native/Libraries/Core/Devtools/symbolicateStackTrace");
       const prettyStack = await symbolicateStackTrace(stack);
+
       if (prettyStack) {
-        const stackWithoutInternalCallsites = prettyStack.filter(
+        let newStack = prettyStack;
+        if (prettyStack.stack) {
+          // This has been changed in an react-native version so stack is contained in here
+          newStack = prettyStack.stack;
+        }
```
Comment (HazAT) [inline src/js/integrations/debugsymbolicator.ts:96]: This is the important change, the stack variable moved in a react native version bump

File: sample/App.js [hunk 2]
```diff
@@ -48,6 +48,34 @@ const App: () => React$Node = () => {
...
+                style={styles.sectionTitle}
+                onPress={() => {
+                  throw new Error('throw new error test');
+                }}>
+                throw new Error
+              </Text>
+              <Text
+                style={styles.sectionTitle}
+                onPress={() => {
+                  Sentry.nativeCrash();
```
Comment (marandaneto) [inline sample/App.js:75]: L: don't need to be in this PR, but if `nativeCrash` is enabled, it means we are able to capture Java/Kotlin and C/C++ errors, would it make sense to have a sample for this too?
