### PR TITLE
Use direct reference to node

### LINKED ISSUE #3472: Xcode scripts should not use `node` from path
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [x]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.15.1

**`react-native` version:** 0.73.0
**`xcode` version:** 15

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
    Sentry.init({
      dsn: 'https://<>.ingest.sentry.io/<>',

      integrations: [
        new Sentry.ReactNativeTracing({
          // Pass instrumentation to be used as `routingInstrumentation`
          routingInstrumentation,
        }),
```

---
**I have the following issue:**

**Steps to reproduce:**
- initialise new 0.73.0 app
- npx @sentry/wizard@latest -s -i reactNative 
- follow prompts 

**Actual result:**

```
Node found at: /Users/jahead/.nvm/versions/node/v18.16.1/bin/node
+ '[' -z '' ']'
+ export SENTRY_PROPERTIES=sentry.properties
+ SENTRY_PROPERTIES=sentry.properties
+ '[' -z '' ']'
+ export SOURCEMAP_FILE=/Users/jahead/Library/Developer/Xcode/DerivedData/BcsInspectionsMobileApp-hacdehfiinxqoeejynnmlpgagqow/Build/Intermediates.noindex/BcsInspectionsMobileApp.build/Debug-iphoneos/BcsInspectionsMobileApp.build/DerivedSources/main.jsbundle.map
+ SOURCEMAP_FILE=/Users/jahead/Library/Developer/Xcode/DerivedData/BcsInspectionsMobileApp-hacdehfiinxqoeejynnmlpgagqow/Build/Intermediates.noindex/BcsInspectionsMobileApp.build/Debug-iphoneos/BcsInspectionsMobileApp.build/DerivedSources/main.jsbundle.map
+ '[' -z '' ']'
+ SENTRY_CLI_EXECUTABLE=../node_modules/@sentry/cli/bin/sentry-cli
+ REACT_NATIVE_XCODE=../node_modules/react-native/scripts/react-native-xcode.sh
+ [[ '' != true ]]
+ [[ -z '' ]]
+ NO_AUTO_RELEASE=--no-auto-release
+ ARGS='--no-auto-release  '
+ REACT_NATIVE_XCODE_WITH_SENTRY='"../node_modules/@sentry/cli/bin/sentry-cli" react-native xcode --no-auto-release   "../node_modules/react-native/scripts/react-native-xcode.sh"'
+ '[' '' '!=' true ']'
+ /bin/sh -c '"../node_modules/@sentry/cli/bin/sentry-cli" react-native xcode --no-auto-release   "../node_modules/react-native/scripts/react-native-xcode.sh"'
env: node: No such file or directory
```

**Expected result:**
For automatic scripts to work. 

---

What I think is happening here is that sentry is making some incorrect assumptions to how WITH_ENVIRONMENT works.
And environments that do not have a default node installation breaks sentry's automatic scripts.
As environments that are managed by node version managers, i.e. `nvm` may not have a node in the path

For context `xcode.env.local` 
```
export NODE_BINARY=/Users/jahead/.nvm/versions/node/v18.16.1/bin/node
```

While `with-environment.sh`  does expose NODE_BINARY it does not put node on the path, and if node is not on the path when xcode runs the phase because we are using a node manager the sentry scripts will crash
You can actually fix the issue with `sentry-xcode.sh` with
``` diff
diff --git a/node_modules/@sentry/react-native/scripts/sentry-xcode.sh b/node_modules/@sentry/react-native/scripts/sentry-xcode.sh
index bf024ea..ddca86e 100755
--- a/node_modules/@sentry/react-native/scripts/sentry-xcode.sh
+++ b/node_modules/@sentry/react-native/scripts/sentry-xcode.sh
@@ -19,7 +19,7 @@ ARGS="$NO_AUTO_RELEASE $SENTRY_CLI_EXTRA_ARGS $SENTRY_CLI_RN_XCODE_EXTRA_ARGS"
 REACT_NATIVE_XCODE_WITH_SENTRY="\"$SENTRY_CLI_EXECUTABLE\" react-native xcode $ARGS \"$REACT_NATIVE_XCODE\""
 
 if [ "$SENTRY_DISABLE_AUTO_UPLOAD" != true ]; then
-  /bin/sh -c "$REACT_NATIVE_XCODE_WITH_SENTRY"
+  /bin/sh -c "$NODE_BINARY $REACT_NATIVE_XCODE_WITH_SENTRY"
 else
   echo "SENTRY_DISABLE_AUTO_UPLOAD=true, skipping sourcemaps upload"
   /bin/sh -c "$REACT_NATIVE_XCODE"
```

By adding in the `$NODE_BINARY` in the script call. 
For `sentry-xcode-debug-files.sh` is a bit more tricky, while I'm not 100% on the cause but from reading the script the issue is the that when using the WITH_ENV script inside the `sentry-xcode-debug-files.sh` it is isn't able to read the xcode.env which defaults to `NODE_BINARY=$(command -v node)` which would require the system to have a default node.

I got this working by, running the WITH_ENV script in the phase like so

``` bash
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"

/bin/sh -c "$WITH_ENVIRONMENT ../node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh"
```

``` diff
diff --git a/node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh b/node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh
index 73ab003..5203fc5 100755
--- a/node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh
+++ b/node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh
@@ -5,12 +5,6 @@
 # print commands before executing them and stop on first error
 set -x -e
 
-# load envs if loader file exists (since rn 0.68)
-WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
-if [ -f "$WITH_ENVIRONMENT" ]; then
-    . "$WITH_ENVIRONMENT"
-fi
-
 [ -z "$SENTRY_PROPERTIES" ] && export SENTRY_PROPERTIES=sentry.properties
 [ -z "$SENTRY_CLI_EXECUTABLE" ] && SENTRY_CLI_EXECUTABLE="../node_modules/@sentry/cli/bin/sentry-cli"
 
@@ -21,7 +15,7 @@ EXTRA_ARGS="$SENTRY_CLI_EXTRA_ARGS $SENTRY_CLI_DEBUG_FILES_UPLOAD_EXTRA_ARGS $IN
 UPLOAD_DEBUG_FILES="\"$SENTRY_CLI_EXECUTABLE\" debug-files upload $EXTRA_ARGS \"$DWARF_DSYM_FOLDER_PATH\""
 
 if [ "$SENTRY_DISABLE_AUTO_UPLOAD" != true ]; then
-  /bin/sh -c "$UPLOAD_DEBUG_FILES"
+  /bin/sh -c "$NODE_BINARY $UPLOAD_DEBUG_FILES"
 else
   echo "SENTRY_DISABLE_AUTO_UPLOAD=true, skipping debug files upload"
 fi

```
Lastly, you are missing setting up the input files on `Upload Debug Symbols to Sentry` on the automatic installation

```
			inputPaths = (
				"$(SRCROOT)/.xcode.env.local",
				"$(SRCROOT)/.xcode.env",
			);
```

This will allow sentry to follow the same behavior that react native is following.

---

So TLDR: 
* sentry isn't able to find node for systems that are using a node version manager
* sentry currently can be using a different node version then what is set in the xcode.env

### PR DESCRIPTION
**Pull request by lucas-zimerman**
Fixes #3472

## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: scripts/sentry-xcode.sh [hunk 1]
```diff
@@ -22,7 +22,7 @@ if [ "$SENTRY_DISABLE_AUTO_UPLOAD" != true ]; then
   /bin/sh -c "$REACT_NATIVE_XCODE_WITH_SENTRY"
 else
   echo "SENTRY_DISABLE_AUTO_UPLOAD=true, skipping sourcemaps upload"
-  /bin/sh -c "$REACT_NATIVE_XCODE"
+  /bin/sh -c "$NODE_BINARY $REACT_NATIVE_XCODE_WITH_SENTRY"
```
Comment (krystofwoldrich) [inline scripts/sentry-xcode.sh:25]: H: This else branch is when Sentry is disabled, we should execute the scripts as RN does. Also it's a shell script, so node would failed.

```suggestion
/bin/sh -c "$REACT_NATIVE_XCODE"
```

File: scripts/sentry-xcode-debug-files.sh [hunk 2]
```diff
@@ -21,7 +21,7 @@ EXTRA_ARGS="$SENTRY_CLI_EXTRA_ARGS $SENTRY_CLI_DEBUG_FILES_UPLOAD_EXTRA_ARGS $IN
 UPLOAD_DEBUG_FILES="\"$SENTRY_CLI_EXECUTABLE\" debug-files upload $EXTRA_ARGS \"$DWARF_DSYM_FOLDER_PATH\""
 
 if [ "$SENTRY_DISABLE_AUTO_UPLOAD" != true ]; then
-  /bin/sh -c "$UPLOAD_DEBUG_FILES"
+  /bin/sh -c "$NODE_BINARY $UPLOAD_DEBUG_FILES"
```
Comment (krystofwoldrich) [inline scripts/sentry-xcode-debug-files.sh:24]: We should wrap the node binary so paths with white spaces do not cause issues. But with that, we have to make sure the `NODE_BINARY` is always defined otherwise `'' 'sentry-cli'` will fail to execute.

```suggestion
  /bin/sh -c "\"$NODE_BINARY\" $UPLOAD_DEBUG_FILES"
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,10 @@
 
 ## Unreleased
 
+### Fixes
+
+- Use direct reference to node ([#3493](https://github.com/getsentry/sentry-react-native/pull/3493))
+=======
```
Comment (lucas-zimerman) [inline CHANGELOG.md:8]: ```suggestion```

Comment (lucas-zimerman) [inline CHANGELOG.md:8]:
```suggestion
```

File: scripts/sentry-xcode.sh [hunk 4]
```diff
@@ -23,10 +23,10 @@ ARGS="$NO_AUTO_RELEASE $SENTRY_CLI_EXTRA_ARGS $SENTRY_CLI_RN_XCODE_EXTRA_ARGS"
 REACT_NATIVE_XCODE_WITH_SENTRY="\"$SENTRY_CLI_EXECUTABLE\" react-native xcode $ARGS \"$REACT_NATIVE_XCODE\""
 
 if [ "$SENTRY_DISABLE_AUTO_UPLOAD" != true ]; then
-  /bin/sh -c "$REACT_NATIVE_XCODE_WITH_SENTRY"
+  /bin/sh -c "\"$LOCAL_NODE_BINARY\" $REACT_NATIVE_XCODE_WITH_SENTRY"
 else
   echo "SENTRY_DISABLE_AUTO_UPLOAD=true, skipping sourcemaps upload"
-  /bin/sh -c "$REACT_NATIVE_XCODE"
+  /bin/sh -c "$\"$LOCAL_NODE_BINARY\" $REACT_NATIVE_XCODE_WITH_SENTRY"
```
Comment (krystofwoldrich) [inline scripts/sentry-xcode.sh:29]: `REACT_NATIVE_XCODE` is a shell script.

```suggestion
  /bin/sh -c "$REACT_NATIVE_XCODE"
```

**Review by krystofwoldrich — APPROVED** [review]

**Comment by krystofwoldrich** [comment]
Looks good 🚀, thank you.
